### ISSUE TITLE
[bug]帖子显示不全

### ISSUE THREAD

**Issue by imqishi** [paper777/yamb#13]
帖子中凡是出现了 -- 下面的内容会全部消失，只显示附件

如下图中 私信微信联系吧 这一行就被隐藏掉了

其他帖子也有此问题

![2018-02-03 12 50 23](https://user-images.githubusercontent.com/9132584/35763168-efd9629c-08e0-11e8-8b1a-00b4baa13062.png)
![2018-02-03 12 51 32](https://user-images.githubusercontent.com/9132584/35763173-fd5f219a-08e0-11e8-8073-06823b493bbf.png)

**Comment by paper777** [comment]
fixed
