### ISSUE TITLE
api for mail

### ISSUE THREAD

**Issue by paper777** [paper777/yamb#2]
# 1. get mail list
### URL
> /b/mail/:type.json

`type`: enum of `inbox`, `outbox`, `deleted`

### METHOD
GET

---

# 2. get mail
### URL
> /b/mail/:type/show/:num.json

`num`: mail id/num

### METHOD
GET

---

#  3. send a mail
### URL
> /b/mail/send.json

### METHOD
POST

### PARAMS
post form data:

|name|type|required|desc|
|---|---|---|---|
|title|string|true|--|
|content|string|true|--|
|id|int|true|tartget account id,like`paper777`|

---

# 4. reply a mail
### URL
> /b/mail/:type/send/:num.json

### METHOD
POST

### PARAMS
post form data:

|name|type|required|desc|
|---|---|---|---|
|title|string|true|--|
|content|string|true|--|

---

# 5. forward a mail
### URL
> /b/mail/:type/forward/:num.json

### METHOD
POST

### PARAMS
post form data:

|name|type|required|desc|
|---|---|---|---|
|target|int|true|tartget account id,like`paper777`|

---

# 6. delete a mail
### URL
> /b/mail/:type/delete/:num.json

### METHOD
POST

**Comment by changrui0608** [comment]
1. 邮件转发（forward）
    - 接口所需参数为`target`，而非`id`
    - 使用target做为参数转发，返回response是错误，但测得收件箱收到了转发后的信件
		```Error occured while trying to proxy to: localhost:8080/paper/nforum/n/b/mail/inbox/forward/0.json```

2. 邮件列表
    - 获取到的所有邮件时间都为”1970-01-01”（字符串），但读邮件详细内容(show mail)时间正常

@paper777

**Comment by paper777** [comment]
done

**Comment by paper777** [comment]
`使用target做为参数转发，返回response是错误，但测得收件箱收到了转发后的信件
Error occured while trying to proxy to: localhost:8080/paper/nforum/n/b/mail/inbox/forward/0.json
`
这个问题可以暂时忽略， 测试站 apache 老版本的bug
