### ISSUE TITLE
分区 & 版面搜索

### ISSUE THREAD

**Issue by paper777** [paper777/yamb#4]
分区页面
版面搜索入口

**Comment by imqishi** [comment]
![image](https://user-images.githubusercontent.com/9132584/29747338-1b46de76-8b2a-11e7-9c67-771844d035e4.png)

![image](https://user-images.githubusercontent.com/9132584/29747297-214ede74-8b28-11e7-8360-e29c252472c6.png)

![image](https://user-images.githubusercontent.com/9132584/29747302-352f50fe-8b28-11e7-80e6-6a20ff9e112a.png)


竖线这样可以嘛

中文搜索已解决，需先urldecode再转码。其他地方用的时候也注意下

**Comment by paper777** [comment]
done
